# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\file_browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_file_browser_window(object):
    def setupUi(self, file_browser_window):
        file_browser_window.setObjectName("file_browser_window")
        file_browser_window.resize(723, 598)
        self.verticalLayout = QtWidgets.QVBoxLayout(file_browser_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.open_browser_button = QtWidgets.QPushButton(file_browser_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_browser_button.sizePolicy().hasHeightForWidth())
        self.open_browser_button.setSizePolicy(sizePolicy)
        self.open_browser_button.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setKerning(True)
        self.open_browser_button.setFont(font)
        self.open_browser_button.setObjectName("open_browser_button")
        self.horizontalLayout.addWidget(self.open_browser_button)
        self.root_directory_line_edit = QtWidgets.QLineEdit(file_browser_window)
        self.root_directory_line_edit.setObjectName("root_directory_line_edit")
        self.horizontalLayout.addWidget(self.root_directory_line_edit)
        self.populate_button = QtWidgets.QPushButton(file_browser_window)
        self.populate_button.setObjectName("populate_button")
        self.horizontalLayout.addWidget(self.populate_button)
        self.horizontalLayout.setStretch(1, 4)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.file_tree_widget = QtWidgets.QTreeWidget(file_browser_window)
        self.file_tree_widget.setObjectName("file_tree_widget")
        self.file_tree_widget.headerItem().setText(0, "1")
        self.file_tree_widget.header().setVisible(False)
        self.horizontalLayout_2.addWidget(self.file_tree_widget)
        self.preview_label = QtWidgets.QLabel(file_browser_window)
        self.preview_label.setText("")
        self.preview_label.setObjectName("preview_label")
        self.horizontalLayout_2.addWidget(self.preview_label)
        self.horizontalLayout_2.setStretch(1, 5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(file_browser_window)
        QtCore.QMetaObject.connectSlotsByName(file_browser_window)

    def retranslateUi(self, file_browser_window):
        _translate = QtCore.QCoreApplication.translate
        file_browser_window.setWindowTitle(_translate("file_browser_window", "File Browser"))
        self.open_browser_button.setText(_translate("file_browser_window", "..."))
        self.populate_button.setText(_translate("file_browser_window", "Populate"))
